elastic:
 build: elastic
 ports:
  - 9200

logstash:
 build: logstash
 ports:
  - 3333
 links:
  - elastic
 command: logstash -f /config-dir/logstash.conf

emfiplogprocessor:
 build: emfip_log_processor
 links:
  - logstash
 volumes:
  - input-dir:/input-dir

kibana:
 build: kibana
 links:
  - elastic:elasticsearch
 ports:
  - 5601:5601

